### PR TITLE
Qr code scrum61

### PR DESCRIPTION
**Pull request by isabelle-grimesey-tamu**

### CODE REVIEW

**Comment by Daniel14676** [comment]
looks good, needs some comments

**Comment by Daniel14676** [comment]
Ah, okay. Sounds like a plan (but don't forget to also add comments of course, lol)

**Comment by isabelle-grimesey-tamu** [comment]
Don't merge yet; I'm going to add an easier test that will probably pass (specifically, testing for the presence of the QR code rather than the validity of the QR code).

**Comment by Daniel14676** [comment]
Ah, okay. Sounds like a plan (but don't forget to also add comments of course, lol)

**Comment by jonas-la** [comment]
This meets the coding standard, the linter looks good!

**Comment by adam-pinto** [comment]
Everything looks good to me, linter output checked out and seems like all your changes adhere to the coding standard.

**Pull request merged**
